module.exports = {
  email: 'Email',
  password: 'Password',
  loginWithEmail: 'Log in with Email',
  logout: 'Log out',
  staff: 'Staff',
  roster: 'Roster',
  settings: 'Settings',
  add: 'Add',
  remove: 'Remove',
  edit: 'Edit',
  addedAt: 'Added At',
  hr: 'hr',
  firstName: 'First Name',
  lastName: 'Last Name',
  payRate: 'Pay Rate',
  done: 'Done',
  addStaff: 'Add Staff',
};
